version: "3"
services:
  dbpostgres:
    container_name: postgres
    image: postgres
    hostname: postgres
    volumes:
      - ./DOCKER/POSTGRES/var/:/var/lib/postgresql
      - ./DBMOCKUP/:/home/DBMOCKUP
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    hostname: pgadmin
    ports:
      - 8888:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=fabio@prada.ch
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./DOCKER/REDIS/:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8889:8081"
  caddy:
    image: caddy:2.0.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./DOCKER/CADDY/sites/:/srv
      - ./DOCKER/CADDY/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
